cloneConcurrency: 16

enableGlobalCache: true

enableHyperlinks: true

enableMessageNames: true

enableMirror: true

initFields:
  version: 0.0.1
  author: Cris Mihalache <f3rno64@gmail.com>
  engines:
    node: ">=16.0.0"
  license: MIT
  private: true

networkConcurrency: 16

nmMode: hardlinks-local

nodeLinker: node-modules

preferInteractive: true

progressBarStyle: simba

yarnPath: .yarn/releases/yarn-3.6.0.cjs
